# Generated by Django 5.2.4 on 2025-11-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de jeune fille')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('death_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de décès')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('accomplishments', models.TextField(blank=True, verbose_name='Accomplissements')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('education', models.TextField(blank=True, verbose_name='Formation/Éducation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='family_tree.person', verbose_name='Père')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='family_tree.person', verbose_name='Mère')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Date de mariage')),
                ('marriage_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de mariage')),
                ('divorce_date', models.DateField(blank=True, null=True, verbose_name='Date de divorce')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('spouse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse1', to='family_tree.person')),
                ('spouse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse2', to='family_tree.person')),
            ],
            options={
                'verbose_name': 'Mariage',
                'verbose_name_plural': 'Mariages',
            },
        ),
    ]
