# Generated by Django 5.2.4 on 2025-11-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='spouse_of',
            field=models.ForeignKey(blank=True, help_text="Si cette personne a épousé un membre de la famille (mais n'est pas de la lignée sanguine)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse', to='family_tree.person', verbose_name='Conjoint(e) de'),
        ),
    ]
